FROM python:3.10-slim

WORKDIR /usr/src/app
COPY requirements.txt .

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["bash", "-c", "chmod +x ./download_notebooks.sh && ./download_notebooks.sh && jupyter-book build ."]